# Exclude hidden files, init, tensorrt folders, protobuf generated files, markdown files, and DB model.py files
exclude: ^(.*/\..*|.*__init__.py|.*tensorrt.*|.*_pb2.py|.*.md|.*.database.*.models.py)$
default_language_version:
  python: python3.9
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: no-commit-to-branch  # Prevents direct commits to master
  - id: check-ast  # check if valid python file
  - id: check-merge-conflict  # check if left in merge conflict lines
  - id: debug-statements  # check if left in debug statements
  - id: trailing-whitespace  # remove trailing whitespace
  - id: end-of-file-fixer  # have one line at end of file
  - id: check-docstring-first  # File comments should come before imports
  - id: check-json  # make sure valid json
  - id: check-yaml  # make sure valid yaml
  - id: name-tests-test  # check that tests start with test_*
    args: ['--django']
  - id: requirements-txt-fixer  # sort requirements
  - id: check-added-large-files  # check that we're not committing big files to git, excluding lfs files.
    args: ['--maxkb=1000']  # set max file size to 1000KB
- repo: https://github.com/asottile/pyupgrade  # use Python3 tricks
  rev: v2.2.0
  hooks:
  - id: pyupgrade
    args: ['--keep-percent-format']
- repo: https://github.com/asottile/seed-isort-config  # Helps isort determine third party imports
  rev: v2.1.1
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort  # Sort imports, similar to PyCharm organize imports
  rev: v4.3.21
  hooks:
  - id: isort
    args: ['-l=120', '-m=2']
- repo: https://github.com/pre-commit/mirrors-autopep8  # Autoenforce easy pep8 changes.
  rev: v1.5.1
  hooks:
  - id: autopep8
    args: ['-i', '--max-line-length=120', '--ignore=W504']  # W504 is outdated and conflicts with W503
- repo: https://gitlab.com/pycqa/flake8  # Check for pep8. Autopep8 won't fix everything.
  rev: 3.7.9
  hooks:
  - id: flake8
    args: ['--max-line-length=120', '--ignore=W504']  # W504 is outdated and conflicts with W503
- repo: https://github.com/aflc/pre-commit-jupyter
  rev: v1.1.0
  hooks:
    - id: jupyter-notebook-cleanup
      args:
        - --remove-kernel-metadata
        - --pin-patterns
        - "[pin];[donotremove]"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
    -   id: mypy
        additional_dependencies:
          - types-protobuf==3.17.4
          - types-cachetools
          - types-ujson
          - types-requests
          - numpy
        args:
          - --config-file=.mypy.ini
          - --ignore-missing-imports  # silence all import errors from untyped libraries
          - --follow-imports=silent  # follow imports but suppress all errors
          - --strict  # enable strict flags (e.g. untyped calls, decorators, optional)
          - --allow-subclassing-any  # allow subclassing from classes in silenced modules
          - --show-column-numbers  # add column offsets to error messages
          - --allow-untyped-decorators # allow decorating typed functions with untyped decorators (such as nuplan_test)
