load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "__init__",
    srcs = ["__init__.py"],
)

py_library(
    name = "cloud_tab_js_code",
    srcs = ["cloud_tab_js_code.py"],
)

py_library(
    name = "scenario_tab_js_code",
    srcs = ["scenario_tab_js_code.py"],
)

py_library(
    name = "histogram_tab_js_code",
    srcs = ["histogram_tab_js_code.py"],
)
