load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "sequential_lr_scheduler",
    srcs = ["sequential_lr_scheduler.py"],
    deps = [],
)
