# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nuplan.submission.challenge_pb2 as challenge__pb2


class DetectionTracksChallengeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializePlanner = channel.unary_unary(
                '/challenge_protocol.DetectionTracksChallenge/InitializePlanner',
                request_serializer=challenge__pb2.PlannerInitializationLight.SerializeToString,
                response_deserializer=challenge__pb2.Empty.FromString,
                )
        self.ComputeTrajectory = channel.unary_unary(
                '/challenge_protocol.DetectionTracksChallenge/ComputeTrajectory',
                request_serializer=challenge__pb2.PlannerInput.SerializeToString,
                response_deserializer=challenge__pb2.Trajectory.FromString,
                )


class DetectionTracksChallengeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializePlanner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeTrajectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionTracksChallengeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializePlanner': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializePlanner,
                    request_deserializer=challenge__pb2.PlannerInitializationLight.FromString,
                    response_serializer=challenge__pb2.Empty.SerializeToString,
            ),
            'ComputeTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeTrajectory,
                    request_deserializer=challenge__pb2.PlannerInput.FromString,
                    response_serializer=challenge__pb2.Trajectory.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'challenge_protocol.DetectionTracksChallenge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DetectionTracksChallenge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializePlanner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/challenge_protocol.DetectionTracksChallenge/InitializePlanner',
            challenge__pb2.PlannerInitializationLight.SerializeToString,
            challenge__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ComputeTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/challenge_protocol.DetectionTracksChallenge/ComputeTrajectory',
            challenge__pb2.PlannerInput.SerializeToString,
            challenge__pb2.Trajectory.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
