load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_cached_scenario",
    size = "small",
    srcs = ["test_cached_scenario.py"],
    deps = [
        "//nuplan/planning/scenario_builder/cache:cached_scenario",
    ],
)
